config/routes.rb
Mystore::Application.routes.draw do
  root  'static_pages#home'

  resources :carts, only: :show
  resources :news, only: [:index, :show]
  
  resources :orders, only: [:create, :show] do 
    get 'pdf/:id', to: 'orders#pdf', as: :pdf, on: :collection
  end
  
  resources :products, only: [:show, :index] do
    get :search, on: :collection
  end
  resources :info_pages, :path => "information", only: :show

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  post '/callback', to: 'static_pages#callback'
  post '/gauger', to: 'static_pages#gauger'
 
  resources :subscribers

  match '/xml', to: 'static_pages#xml', via: 'get'

  match '/admin', to: 'admin#admin', via: 'get'
  match '/admin/edit/header', to: 'admin#edit_header', via: 'get', as: :edit_header
  match '/admin/edit/footer', to: 'admin#edit_footer', via: 'get', as: :edit_footer
  match '/admin/edit/product_page_content', to: 'admin#edit_product_page_content', via: 'get', as: :edit_product_content
  match '/admin/edit/news', to: 'admin#edit_news', via: 'get', as: :edit_news
  match '/admin/edit/main_page_content', to: 'admin#edit_mp_content', via: 'get', as: :edit_mp_content
  match '/admin/edit/cart_content', to: 'admin#edit_cart', via: 'get', as: :edit_cart_content
  match '/admin/site_options', to: 'admin#site_options', via: 'get', as: :site_options
  match '/admin/edit/catalog_content', to: 'admin#edit_catalog_content', via: 'get', as: :edit_catalog_content
  match '/cart', to: 'carts#show', via: 'get'
  match '/catalog(/:id)', to: 'products#index', via: 'get', as: 'catalog'
  match '/admin/edit/emails', to: 'admin#edit_emails', via: 'get', as: :edit_emails

  scope '/admin' do 
    resource :general_content, :controller => :general_content, only: :update
    resource :site_options, only: :update
    resource :catalog, :controller => :catalog, only: [:edit, :update]
    resource :slider, :controller => :slider, only: [:edit, :update]
    resources :slides
    resources :chosen_products
    resources :features_templates
    resources :news, except: [:index, :show]
    resources :orders, except: [:create, :show]

    resources :categories, except: :index do
      get :search, on: :collection
    end
    resources :features do
      get :search, on: :collection
      get :search_values, on: :collection
    end
    resources :products, except: [:show, :index] do
      get :admin_search, on: :collection
      get :admin_index, as: :admin, on: :collection
      patch :hide_product, on: :collection
      post :batch_action, on: :collection
    end
    resources :info_pages, :path => "information", except: :show do
      patch :update_subcategory_order, on: :collection
      get :admin_index, on: :collection, as: :admin
    end
    
  end

  

end

app/controllers/static_pages_controller.rb
# -*- encoding : utf-8 -*-
class StaticPagesController < ApplicationController
  def home
  	@mp_presenter = MainPagePresenter.new   
  end
  
  def maintenance
    render layout: 'simple'
  end
  def callback
    client = {name: params[:name], phone: params[:phone], time: params[:time]}
    Mailer.callback(client).deliver
    render nothing: true
  end
  def gauger
    client = {first: params[:first], second: params[:second],
     phone: params[:phone], email: params[:email], comment: params[:comment]}
    Mailer.gauger(client).deliver
    render nothing: true
  end
  def xml
    require 'pricelist'
    render xml: Pricelist::generate
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_catalog.html.erb
<nav class="s-nav">
	<h2><%= link_to 'Каталог', catalog_path, class: 'cat-link' %></h2>
	<ul id="catalog">
		<% Category.where(prev_id: nil, hidden: false).order(:order).each do |main| %>
			<li>
				<%= link_to main.name, catalog_path(main.id),  class: 'main' + (main.special ? ' special' : '') %>
				<% if Category.where(prev_id: main.id).exists? %>
					<ul>
						<% Category.where(prev_id: main.id, hidden: false).order(:order).each do |c| %>
							<li>
								<%= link_to c.name, catalog_path(c.id),  class: (main.special ? ' special' : '') %>
							</li>
						<% end %>
					</ul>
				<% end %>
			</li>
		<% end %>
	</ul>
</nav>

app/views/static_pages/call.html.erb
<fieldset>
	<legend>Заполните форму</legend>
		<%= form_for @call do |f| %>
			<%= f.label :second, 'Ваша фамилия' %>
			<%= f.text_field :second%> 

			<%= f.label :first, 'Имя' %>
			<%= f.text_field :first%> 

			<%= f.label :phone, 'Контактный телефон' %>
			<%= f.phone_field :phone%> 

			<%= f.submit 'Отправить' %>
		<% end %>
</fieldset>

app/views/static_pages/get_slide_form.html.erb
<div>
		<%= form_for Slide.new, remote: true, class: 'slide' do|f| %>

			<img />	
			<%= label :image, 'Выберите изображение' %>
			<%= f.file_field :image %>	
			<%= f.label :description, 'Описание слайда' %>
			<%= f.text_field :description  %>
			

		<% end %>
</div>

app/views/static_pages/header_edit.html.erb
<%= params %>

app/views/static_pages/home.html.erb
<aside>
	<%= render partial: 'layouts/catalog' %>

	<% if (CONFIG[:news] and NewsItem.any?) or current_user.try(:admin?) %>
		<div class="aside-news">
			<h3>
				Новости
				<% if current_user.try(:admin?) %>
					<%= link_to image_tag('settings_white.png'), edit_news_path, class: 'edit-news-item' %>
				<% end %>
			</h3>

			<% NewsItem.last(2).reverse.each do |news_item| %>
				<div class="news-item">
					<h4>
						<%= link_to news_index_path(:anchor => "news_#{news_item.id-1}") do %>
							<%= news_item.headline %>
							<span><%= news_item.created_at.strftime("%d.%m.%Y") %></span>
						<% end %>
					</h4>
					
					<%= image_tag(news_item.image.url(:small)) if  news_item.image.exists? %>
					<p> <%= news_item.description %> </p>
				</div>
			<% end %>

			<%= link_to 'Просмотреть все', news_index_path, style: 'padding-bottom: 20px;' %>

		</div>	
	<% end %>
</aside>
<main id="main" class="r-aside">
	<h2 class="m-header">Популярные товары</h2>
	<% @mp_presenter.main_categories.each do |main_cat| %>
		<% if @mp_presenter.products(main_cat).any? %>
			<h3 class="cat-header"><%= link_to main_cat.title, catalog_path(main_cat) %></h3>
			<div class="cat-products">
			
				<% @mp_presenter.products(main_cat).each do |prod| %>
					<%= render partial: 'products/product', locals: {page: 'main', product: prod} %>
				<% end %>

			</div>
		<% end %>
	<% end %>
	<div class="main-bottom">
		<% if current_user.try(:admin?) %>
			<%= form_tag({:controller => :general_content, :action => :update}, :method => :patch, :remote => true) do %>
				<%= text_area :general_content, :main_page_content, data: {toolbar: 'ContentEditInline'}, class: "inline-area" %>
				<div class="inline-content">
					<%= @mp_presenter.content.html_safe %>
				</div>
			<% end %>
		<% else %>
			<%= @mp_presenter.content.html_safe %>
		<% end %>
	</div>
</main>

<% content_for :admin_menu do %>
	<li>
		<%= link_to 'Настройка каталога', edit_catalog_path %>
	</li>
	<li>
		<%= link_to 'Управление новостями', edit_news_path %>
	</li>
	<li>
		<%= link_to 'Настроить слайдер', edit_slider_path %>
	</li>
	<li>
		<%= link_to 'Управление контентом', edit_mp_content_path %>
	</li>
	<li>
		<p>Вы также можете изменить текст, следующий после списка товаров, не уходя с данной страницы.</p>
	</li>
<% end %>

<% content_for :title do %>
	<%= @mp_presenter.title  %>
<% end %>

<% content_for :meta do %>
	<meta name="Description" content="<%= @mp_presenter.description %>" >
	<meta name="Keywords" content="<%= @mp_presenter.keywords %>">
<% end %>

<% content_for :divider do %>
	<div class="slider-wrapper">
		<div class="slider-container">
			<ul id="sb-slider" class="sb-slider">
				<% SimpleSlide.all.each do |slide| %>
 				    <li>
 				    	<%= link_to slide.link do %>
 				    		<%= image_tag slide.image.url(:normal) %>
 				    	<% end %>
 				    </li>
 				<% end %>
 			</ul>			
		</div>
	</div>
<% end %>

app/views/static_pages/maintenance.html.erb
<div class="row">
	<p class="open-soon-admin"><%= link_to 'админ?', new_user_session_path %></p>
</div>

<div class="row">
	<div class="small-11 small-centered columns">
		<div class="open-soon-wrapper">
			<h1>Скоро открытие!</h1>
			<h3>Интернет магазин дверей и обоев "Двери возим" находится в разработке</h3>
			<%= form_tag '/subscribers', :id => 'mail_form', :data => {abide: '', type: 'json'}, :remote => true, :method => :post do %>
				<p> Мы можем уведомить вас об открытии, для этого введите свой e-mail в поле ниже. </p>
				<div class="row">
					<div class="small-13 columns">
						<%= email_field_tag :new_mail, '', :placeholder => 'Введите свой e-mail', :required => true %>
						<small class="error">Пожалуйста введите адрес электронной почты</small>
					</div>
					<div class="small-3 columns">
						<%= content_tag :button, 'Отправить запрос', :type => 'submit', :class => 'open-soon-add-email', data: { disable_with: 'Submitting...' } %></div>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/static_pages/site_options.html.erb
<div class="row">
	<div class="medium-12 columns">
		<fieldset>
			<legend>Слайдер</legend>
			<%= form_for SiteOption.find_by(name: 'show_slider') do |f| %>
				<p>'Отображать' слайдер на главной странице?</p>
					<%= f.radio_button :value, 'on' %> <%=label_tag :value, 'да' %>
					<%= f.radio_button :value, 'off' %> <%=label_tag :value, 'нет' %>
			<% end %>
			<p>Настройка слайдов</p>
				<%=content_tag :a, 'Добавить слайд', class: 'add-slide' %>
				<%Slide.all.each do |slide| %>
					<%= form_for slide, remote: true, class: 'slide' do |f|%>
						<%=image_tag slide.image.url %>
						<%=f.label :image, 'Изменить картинку' %>
						<%=f.file_field :image %>
						<%=f.label :description, 'Описание слайда' %>
						<%=f.text_field :description %>
					<% end %>
				<% end %>
			</fieldset>
		<fieldset>
			<legend>Новости</legend>
			<%= form_for SiteOption.find_by(name: 'show_news') do |f| %>
			<p>Отображать новости на главной странице?</p>
					<%= f.radio_button :value, 'on' %> <%=label_tag :value, 'да' %>
					<%= f.radio_button :value, 'off' %> <%=label_tag :value, 'нет' %>
			<% end %>
		</fieldset>
		<%= button_tag 'Сохранить изменения', type: 'button', class: 'save-site-opt' %>
	</div>
</div>