config/routes.rb
Mystore::Application.routes.draw do
  root  'static_pages#home'

  resources :carts, only: :show
  resources :news, only: [:index, :show]
  
  resources :orders, only: [:create, :show] do 
    get 'pdf/:id', to: 'orders#pdf', as: :pdf, on: :collection
  end
  
  resources :products, only: [:show, :index] do
    get :search, on: :collection
  end
  resources :info_pages, :path => "information", only: :show

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  post '/callback', to: 'static_pages#callback'
  post '/gauger', to: 'static_pages#gauger'
 
  resources :subscribers

  match '/xml', to: 'static_pages#xml', via: 'get'

  match '/admin', to: 'admin#admin', via: 'get'
  match '/admin/edit/header', to: 'admin#edit_header', via: 'get', as: :edit_header
  match '/admin/edit/footer', to: 'admin#edit_footer', via: 'get', as: :edit_footer
  match '/admin/edit/product_page_content', to: 'admin#edit_product_page_content', via: 'get', as: :edit_product_content
  match '/admin/edit/news', to: 'admin#edit_news', via: 'get', as: :edit_news
  match '/admin/edit/main_page_content', to: 'admin#edit_mp_content', via: 'get', as: :edit_mp_content
  match '/admin/edit/cart_content', to: 'admin#edit_cart', via: 'get', as: :edit_cart_content
  match '/admin/site_options', to: 'admin#site_options', via: 'get', as: :site_options
  match '/admin/edit/catalog_content', to: 'admin#edit_catalog_content', via: 'get', as: :edit_catalog_content
  match '/cart', to: 'carts#show', via: 'get'
  match '/catalog(/:id)', to: 'products#index', via: 'get', as: 'catalog'
  match '/admin/edit/emails', to: 'admin#edit_emails', via: 'get', as: :edit_emails

  scope '/admin' do 
    resource :general_content, :controller => :general_content, only: :update
    resource :site_options, only: :update
    resource :catalog, :controller => :catalog, only: [:edit, :update]
    resource :slider, :controller => :slider, only: [:edit, :update]
    resources :slides
    resources :chosen_products
    resources :features_templates
    resources :news, except: [:index, :show]
    resources :orders, except: [:create, :show]

    resources :categories, except: :index do
      get :search, on: :collection
    end
    resources :features do
      get :search, on: :collection
      get :search_values, on: :collection
    end
    resources :products, except: [:show, :index] do
      get :admin_search, on: :collection
      get :admin_index, as: :admin, on: :collection
      patch :hide_product, on: :collection
      post :batch_action, on: :collection
    end
    resources :info_pages, :path => "information", except: :show do
      patch :update_subcategory_order, on: :collection
      get :admin_index, on: :collection, as: :admin
    end
    
  end

  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :products, through: :chosen_products
	has_many :chosen_products

	def sum
		sum = 0
		chosen_products.each do |p|
			sum += p.quantity * p.current_price
		end
		sum
	end
end

app/controllers/carts_controller.rb
# -*- encoding : utf-8 -*-
class CartsController < ApplicationController
	def show
		@order = Order.new
	end
end

app/helpers/cart_helper.rb
module CartHelper

	def delivery_info
		delivery_info = GeneralContent.find_by(name: 'delivery_info')
		unless delivery_info.blank?
			content_tag :p, delivery_info.content.html_safe, class: 'after-cb'
		end
	end

	def pickup_info
		pickup_info = GeneralContent.find_by(name: 'pickup_info')
		unless pickup_info.blank?
			content_tag :p, pickup_info.content.html_safe, class: 'after-cb'
		end
	end

	def order_info
		order_info = GeneralContent.find_by(name: 'order_info')
		unless order_info.blank?
			order_info.content.html_safe
		end
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_chosen_product.html.erb
<tr>
	<td class="cp-picture">
		<%= image_tag chosen_product.product.basic_image.url(:small) %>
	</td>

	<td>
		<p><%= link_to chosen_product.product.name, product_path(chosen_product.product.id) %></p>
		<p>
			<% chosen_product.text_values.each do |option| %>
				<%= option.feature.name %>: <%= option.text %> <br>
			<% end %>
			<% if (complectation = chosen_product.complectation) %>
				Комплектность: <%= complectation.name %> <br>
			<% end %>
		</p>
	</td>

	<td class="cp-price">
		<%= chosen_product.current_price %> <span class="rouble"><span>руб.</span></span>
	</td>

	<td>
		<% if chosen_product.cart %>
			<%= form_helper.fields_for :chosen_products, chosen_product do |cp_form_helper| %>
				<%= cp_form_helper.number_field :quantity, min: 1, step: 1, class: 'cp-quantity' %>
				<%= cp_form_helper.hidden_field :id %>
			<% end %>
		<% else %>
			<%= chosen_product.quantity %>
		<% end %>
	</td>

	<td class="cp-sum">
		<%= chosen_product.current_price * chosen_product.quantity %> <span class="rouble"><span>руб.</span></span>
	</td>
	<% if @order.new_record? %>
		<td>
			<a class="delete-from-cart" data-id="<%= chosen_product.id %>" title="Удалить товар из корзины">&#215;</a>
		</td>
	<% end %>
</tr>

app/views/carts/_product_in_cart.html.erb
<tr>
	<td>
		<%= image_tag product_in_cart.product.basic_image.url(:small) %>
	</td>

	<td>
		<p><%= link_to product_in_cart.product.name + ' ' + product_in_cart.product.modification, product_path(product_in_cart.product_id) %></p>
		<p>
			<% product_in_cart.text_values.each do |option| %>
				<%= option.feature.name %>: <%= option.text %> <br>
			<% end %>
			<% product_in_cart.pictures.each do |option| %>
				<%= option.feature.name %>: <%= image_tag option.image.url %> <br>
			<% end %>
			<% complectation = product_in_cart.complectations.take %>
			<% if complectation %>
				Комплектность: <%= complectation.name %> <br>
			<% end %>
		</p>
	</td>

	<td>
			<% if complectation %>
				<%= price = complectation.price %> руб.
			<% else %>
				<%= price = product_in_cart.product.price %> руб.
			<% end %>
	</td>

	<td>
			<% if product_in_cart.cart %>
				<%= f.fields_for :products_in_cart, product_in_cart do |pr| %>
					<%= pr.text_field :quantity %>
				<% end %>
			<% else %>
				<%= product_in_cart.quantity %>
			<% end %>
	</td>

	<td>
			<%= price * product_in_cart.quantity %>
	</td>
	<% if product_in_cart.cart %>
		<td>
				<%= button_tag 'удалить', data: {product_id: product_in_cart.id}, type: 'button', class: 'del-from-cart' %>
		</td>
	<% end %>
</tr>

app/views/carts/show.html.erb
<div id="main" class="m-cart">
	
	<% if flash[:create_order_error] %>
		<div class="order-error">
			<%= flash[:create_order_error] %>
		</div>
	<% end %>

	<% if @cart.chosen_products && @cart.chosen_products.exists? %>
		<%= form_for @order do |f| %>
			<table id="chosen_products">
				<thead>
					<tr>
						<th>
							Изображение
						</th>
						<th>
							Товар
						</th>

						<th>
							Цена
						</th>

						<th>
							Количество
						</th>

						<th>
							Итого
						</th>
						<% if @order.new_record? %>
							<th>
								Удалить
							</th>
						<% end %>
					</tr>
				</thead>

				<tbody>
					<%= render partial: "chosen_product", collection: @cart.chosen_products, locals: {form_helper: f} %>
					<tr>
						<td colspan=0 class="total-price">
							Общая сумма заказа: <span id="sum"><%= @cart.sum %></span> <span class="rouble"><span>руб.</span></span>
						</td>
					</tr>
				</tbody>
			</table>

			<div class="section">
				<div class="delivery">
					<%= f.label :delivery, 'Доставка' %>
					<div class="r-button-wrapper">
						<%= f.radio_button :delivery, true, checked: true %> <span>Нужна доставка</span>
					</div>
					<%=	delivery_info %>
					<div class="r-button-wrapper">
						<%= f.radio_button :delivery, false, checked: false %> <span>Самовывоз</span>
					</div>
					<%= pickup_info %>
				</div>
				<div class="address">
					<%= label_tag :address, 'Адрес доставки (опционально, будет уточнен менеджером)' %>
					<%= text_area_tag :address %>
				</div>
			</div>

			<div class="section">
				<div class="payment-method">
					<%= f.label :payment_method, 'Способ оплаты' %>
					<div class="r-button-wrapper">
						<%= f.radio_button :payment_method, 'Наличными', checked: true %> <span>Наличными</span>
					</div>
					<div class="r-button-wrapper">
						<%= f.radio_button :payment_method, 'Безналичный расчет' %> <span>Безналичный расчет</span>
					</div>
				</div>
			</div>

			<div class="section">
				<div class="contacts">
					<label>Контактная информация</label>

					<%= f.text_field :second, required: true, placeholder: 'Ваша фамилия'%> 

					<%= f.text_field :first, required: true, placeholder: 'Имя'%> 

					<%= f.email_field :email, required: true, placeholder: 'E-Mail'%> 

					<%= f.phone_field :phone, required: true, placeholder: 'Контактный телефон'%> 
				</div>
			</div>

			<div class="section">
				<div class="comment">
					<%= f.label :comment, 'Примечание к заказу (опционально)' %>
					<%= f.text_area :comment %>
				</div>
			</div>

			<div class="section">
				<%= order_info %>

			<%= f.submit 'Оформить заказ' %>
			</div>
		<% end %>
	<% else %>
			<h3>Корзина пуста</h3>
	<% end %>
</div>

<% content_for :divider do %>
	<div class="h-divider gray">
		<div class="container">
			<div class="info-category">
				<h4>Корзина</h4>
			</div>
			<div class="route">
				<span>Вы здесь: </span>
				<%= link_to 'Главная страница' %> / 
				Корзина
			</div>
		</div>
	</div>
<% end %>

<% content_for :admin_menu do %>
	<li>
		<%= link_to 'Редактировать контент на странице', edit_cart_content_path %>
	</li>
<% end %>