config/routes.rb
Mystore::Application.routes.draw do
  root  'static_pages#home'

  resources :carts, only: :show
  resources :news, only: [:index, :show]
  
  resources :orders, only: [:create, :show] do 
    get 'pdf/:id', to: 'orders#pdf', as: :pdf, on: :collection
  end
  
  resources :products, only: [:show, :index] do
    get :search, on: :collection
  end
  resources :info_pages, :path => "information", only: :show

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  post '/callback', to: 'static_pages#callback'
  post '/gauger', to: 'static_pages#gauger'
 
  resources :subscribers

  match '/xml', to: 'static_pages#xml', via: 'get'

  match '/admin', to: 'admin#admin', via: 'get'
  match '/admin/edit/header', to: 'admin#edit_header', via: 'get', as: :edit_header
  match '/admin/edit/footer', to: 'admin#edit_footer', via: 'get', as: :edit_footer
  match '/admin/edit/product_page_content', to: 'admin#edit_product_page_content', via: 'get', as: :edit_product_content
  match '/admin/edit/news', to: 'admin#edit_news', via: 'get', as: :edit_news
  match '/admin/edit/main_page_content', to: 'admin#edit_mp_content', via: 'get', as: :edit_mp_content
  match '/admin/edit/cart_content', to: 'admin#edit_cart', via: 'get', as: :edit_cart_content
  match '/admin/site_options', to: 'admin#site_options', via: 'get', as: :site_options
  match '/admin/edit/catalog_content', to: 'admin#edit_catalog_content', via: 'get', as: :edit_catalog_content
  match '/cart', to: 'carts#show', via: 'get'
  match '/catalog(/:id)', to: 'products#index', via: 'get', as: 'catalog'
  match '/admin/edit/emails', to: 'admin#edit_emails', via: 'get', as: :edit_emails

  scope '/admin' do 
    resource :general_content, :controller => :general_content, only: :update
    resource :site_options, only: :update
    resource :catalog, :controller => :catalog, only: [:edit, :update]
    resource :slider, :controller => :slider, only: [:edit, :update]
    resources :slides
    resources :chosen_products
    resources :features_templates
    resources :news, except: [:index, :show]
    resources :orders, except: [:create, :show]

    resources :categories, except: :index do
      get :search, on: :collection
    end
    resources :features do
      get :search, on: :collection
      get :search_values, on: :collection
    end
    resources :products, except: [:show, :index] do
      get :admin_search, on: :collection
      get :admin_index, as: :admin, on: :collection
      patch :hide_product, on: :collection
      post :batch_action, on: :collection
    end
    resources :info_pages, :path => "information", except: :show do
      patch :update_subcategory_order, on: :collection
      get :admin_index, on: :collection, as: :admin
    end
    
  end

  

end

app/models/category.rb
# -*- encoding : utf-8 -*-
class Category < ActiveRecord::Base
	extend FriendlyId
	friendly_id :name, :use => :slugged

	has_attached_file :label, :styles => { :small => "50x50>" },
                  :url  => "/assets/categories/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/categories/:id/:style/:basename.:extension"
	
	has_and_belongs_to_many :products

	has_many :features, -> {order 'categories_features.ordering ASC'}, :through => :categories_features
	has_many :categories_features, class_name: "CategoriesFeatures"
	accepts_nested_attributes_for :features

	belongs_to :category, foreign_key: "prev_id"
	has_many :categories, foreign_key: "prev_id"

	has_one :features_template, through: :category_template
	has_one  :category_template

	def self.get_lasts_parents
		lasts = where(last: true, special: false)
		lasts_parents = where(id: lasts.pluck(:prev_id)).to_a
		last_in_root = lasts.where(prev_id:nil)
		if last_in_root.exists?
			empty_category = Category.new(id: nil, name: 'Без категории')
			empty_category.categories = last_in_root
			lasts_parents.push empty_category
		end
		lasts_parents
	end

	def self.get_first_last_category_prefix
		category = Category.where.not(prev_id:nil).find_by( last: true, special: false )
		category.product_prefix ? category.product_prefix : ""
	end

	def self.special
		where(special: true)
	end

	def style
		style = Array.new
		style.push 'main' if !last || prev_id.nil?
		style.push 'special' if special
		style.join ' '
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :check_user_role
	layout 'admin'

	def search
		@categories = Category.where("name LIKE ?", '%'+params[:search]+'%')
		@categories = @categories.where.not(id: params[:ids])
    	render partial: 'products/category_tr', layout: false, locals: {categories: @categories} 
    end

	def new
		@category = Category.new(prev_id: params[:prev_id])
		render 'form'
	end

	def create
		category = Category.new(category_params)
		category.last = true
		category.features_template = FeaturesTemplate.find_by(id: params[:features_template])

		category.save
		Category.find(category.prev_id).update_attributes(last: false) if category.prev_id
		redirect_to edit_catalog_path
	end

	def edit
		@category = Category.find(params[:id])	
		render 'form'
	end	

	def update
		category = Category.friendly.find(params[:id])
		category.update(category_params)
		category.features_template = FeaturesTemplate.find_by(id: params[:features_template])
		category.save

		render nothing: true
	end
	  
	  private
  		def category_params
   			params.require(:category).permit(:name, :label, :hidden, :special, :visible, :title, :product_prefix,
   			 :description, :prev_id, :meta_description, :keywords)
 		end
end

app/views/categories/_category.html.erb
<% categories.order(:order).each do |cat| %>
	<li data-id="<%= cat.id %>" class="tree-item-wrapper">
		<div class="line">
			<div class="t-category-name">
				<% unless cat.last %>
					<a class="collapse"></a>
				<% end %>
				<span><%= cat.name %></span>
			</div>
			<div class="tree-actions">
				<a class="tree-action delete-category">Удалить</a>
				<%= link_to 'Изменить', edit_category_path(cat.id), class: 'tree-action'%>
				<%= link_to 'Добавить', new_category_path(prev_id: cat.id), title: 'Добавить категорию', class: 'tree-action'%>
			</div>
		</div>
		<ul>
			<% unless cat.last %>
				<%= render partial: 'categories/category', locals: {categories: cat.categories} %>
			<% end %>
		</ul>
	</li>
<% end %>

app/views/categories/form.html.erb
<%= form_for @category, remote: @category.persisted?, :html => { :multipart => true } do |f| %>	
	<div class="block">
		<div class="section header">
			<h3>
				Основные свойства
			</h3>
		</div>

		<div class="section">
			<div class="form-input-2">
				<%= f.label :name, 'Наименование категории:'%>
				<%= f.text_field :name, required: true %>
			</div>
			<div class="form-input-2-l">
				<%= f.label :prev_id, 'Родительская категория:' %>
				<%= f.collection_select :prev_id, Category.all, :id, :name, include_blank: 'Без категории' %>
			</div>
		</div>
		
		<div class="section">
			<div class="form-input-2">
				<%= f.label :title, 'Заголовок:' %>
				<%= f.text_field :title %>
			</div>
			<div class="form-input-2-l">
				<%= f.label :product_prefix, 'Префикс (у товара):' %>
				<%= f.text_field :product_prefix %>
			</div>
		</div>
		<div class="section">
			<div class="form-input-3">
				<%= f.label :special, 'Акция?' %>
				<%= f.check_box :special %>
				<span class="after-cb">Например: новинки, распродажа и т.п.</span>
			</div>
			<div class="form-input-3">
				<%= f.label :hidden, 'Скрытая?' %>
				<%= f.check_box :hidden %>
				<span class="after-cb">Если данное поле отмечено, то категория не будет отображаться в каталоге.</span>
			</div>
			<div class="form-input-3-l">
				<%= f.label :label, 'Ярлык:' %>
				<% if f.object.label.exists? %>
					<%= image_tag  f.object.label.url, id: 'f_label_preview'%>
				<% else %>
					
					<%= tag 'img', id: 'f_label_preview'  %>
				<% end %>
				<%= f.file_field :label, id: 'basic_image' %>
			</div>
		</div>
		<div class="section">
			<div class="form-input-1">
				<%= label_tag :features_template, 'Шаблон характеристик' %>
				<%= select_tag :features_template, options_from_collection_for_select(FeaturesTemplate.all, :id, :name, selected: @category.features_template.try(:id)), prompt: 'Нет' %>
			</div>
		</div>
		<div class="section">
			<div class="form-input-1">
				<%= f.label :description, 'Описание:' %>
				<%= f.text_area :description %>
			</div>
		</div>
		<div class="section">
			<div class="form-input-2">
				<%= f.label :keywords, 'Ключевые слова:' %>
				<%= f.text_field :keywords %>
			</div>
			<div class="form-input-2-l">
				<%= f.label :meta_description, 'Описание (мета):' %>
				<%= f.text_area :meta_description %>
			</div>
		</div>
	</div>
<% end %>
<% content_for :top_bar do%>
	<h2 class="catalog">
		<% if @category.new_record? %>
			Новая категория товаров
		<% else %>
			Редактировать категорию
		<% end %>
	</h2>
<% end %>

<%= 
content_for :top_bar_buttons do
	link_to('Перейти к редактору каталога', edit_catalog_path, class: 'label-button') +
	content_tag(:a, 'Сохранить', data: {form: '#admin_workspace form'}, class: 'label-button submit')
end 
%>